env:
  - >
    container_id=$(mktemp)
    distribution=fedora
    version=30
    init=/sbin/init
    run_opts=""

services:
  - docker

before_install:
  - sudo apt-get update
  - docker pull ${distribution}:${version}

script:
  - ./test/test.sh