env:
  - >
    container_id=$(mktemp)
    distribution=ubuntu
    version=14.04
    init=/sbin/init

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo docker pull ${distribution}:${version}
  - sudo docker build --rm=true --file=test/travis-ci/Dockerfile --tag=${distribution}:ansible test/travis-ci

script:
    # Run container in detached state
  - sudo docker run --detach --volume="${PWD}":/home/ansible/:ro ${distribution}:ansible "${init}" > "${container_id}"

  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook -i /home/ansible/test/travis-ci/test_hosts --syntax-check /home/ansible/playbook.yml
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook -i /home/ansible/test/travis-ci/test_hosts /home/ansible/playbook.yml --connection=local

    # Clean up
  - sudo docker stop "$(cat ${container_id})"
