env:
  - >
    container_id=$(mktemp)
    distribution=centos
    version=7
    init=/usr/lib/systemd/systemd
    run_opts="--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - >
    container_id=$(mktemp)
    distribution=ubuntu
    version=14.04
    init=/sbin/init
    run_opts=""

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo docker pull ${distribution}:${version}
  - sudo docker build --rm=true --file=test/docker/Dockerfile --tag=${distribution}:ansible test/docker

script:
    # Run container in detached state
  - sudo docker run --detach --volume="${PWD}":/home/ansible:ro ${run_opts} ${distribution}:ansible "${init}" > "${container_id}"

  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook -i /home/ansible/test/docker/test_hosts --syntax-check /home/ansible/playbook.yml
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook -i /home/ansible/test/docker/test_hosts /home/ansible/playbook.yml --connection=local --become

    # Clean up
  - sudo docker stop "$(cat ${container_id})"
