---
- name: zsh - cloning  oh-my-zsh
  become: true
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest="/home/{{ item }}/.oh-my-zsh"
  register: oh_my_zsh_cloning
  with_items: "{{ users }}"  
- name: zsh - cloning powerlevel9k
  become: true
  git:
    repo=https://github.com/bhilburn/powerlevel9k.git
    dest="/home/{{ item }}/.oh-my-zsh/custom/themes/powerlevel9k"
  register: powerlevel_cloning  
  with_items: "{{ users }}"
- name: zsh - Generate ~.zshrc
  become: true
  template:
    mode: 0644
    src: zshrc.j2
    owner: "{{ item }}"
    group: "{{ item }}"    
    dest: "/home/{{ item }}/.zshrc"
  register: oh_my_zsh_rc
  when: oh_my_zsh_cloning|changed
  with_items: "{{ users }}"
- name: zsh - make the user the owner of the oh-my-zsh folder
  become: true
  file:
    path: "/home/{{ item }}/.oh-my-zsh"
    owner: "{{ item }}"
    group: "{{ item }}"   
    recurse: yes
  with_items: "{{ users }}"
- name: zsh - add zsh as default shell to the user
  become: true
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  when: oh_my_zsh_rc|changed
  with_items: "{{ users }}"