# Experimental: Depends on signed packages
---
- name: virtualbox - get kernel version
  command: uname -r
  register: kernel_version
  when:
    ansible_distribution  == "Fedora"
#depends on rpm fusion
- name: virtualbox - basic installation
  dnf:
    name: VirtualBox
    state: present
  when:
    ansible_distribution  == "Fedora"
- name: virtualbox - install dependencies
  dnf: name={{ item }} state=present
  with_items:
    - akmod-VirtualBox
    - "kernel-devel-{{ kernel_version.stdout }}"
  when:
    ansible_distribution  == "Fedora"
- name: virtualbox - akmod
  become: true
  shell: "akmods --kernels {{ kernel_version.stdout }} && systemctl restart systemd-modules-load.service"
  when:
    ansible_distribution  == "Fedora"